### PR TITLE
merge my past weeks work (and tobias')

### PR DESCRIPTION
**Pull request by ftalbrecht**
I currently diverge bc. of the purging of the `ConstGridProvider`. At some point though (after the publication) I should get back. This is a reminder for me.

### CODE REVIEW

**Comment by ftalbrecht** [comment]
So, by now we should be ready to merge. I merged the current main master and @tobiasleibner master into my master. As far as I can tell there are three things that had diverged and may possibly break your code:
* I reintroduced the `ConstProviderInterface`. It is now provides only `const GridType& grid() const`, the rest is proided by `ProviderInterface`. It is thus not possible (any more, wrt. my master) to obtain an view/part from a const provider. On the other hand (wrt. the main master) there is only one additional class (re)introduced that does not hurt, the `ProviderInterface` did not loose any functionality, and I can continue to use other (dependent) code. This should not break anything.
* I changed the interface of the linear solvers. While there used to be two `options()`, one returning a string (e.g. the type) and one (taking a type) returning a `Configuration`. Now there is one method `type()` and one `options(const std:string type)`, which should both be obvious. This might break your code, but those have not been used much I think.
* @renemilk added UMFPack support and serial SUPERLU to the ISTL solvers which gave the largest merge conflict for me. I tried to fix it (it compiles for me) but I am quite certain that I can not test it fully. So please **test the linear solvers** in your setup before we merge!

I would like to have this hanging around for another few days to fix (and merge) more dependent code, but please be prepared for the cheange!

**Comment by renemilk** [comment]
Pretty sure we _had_ our own implementation, that was then moved into a namespace, and forwarded...
Imo go ahead and change the current implementation we have and drop the new stuff.

**Comment by renemilk** [comment]
See d25bc49c5c7551063fbf72c783332f67c5fe3542
1b84c7ed0ce187c9f3ee24feddfc6f3448d9d2a4 3930c9f46623f4f0c92f240bdde001920514b6a0 02116070fc658e96b455d7f35f5ba468001fe844 fd2b5e4e49d1d90a1ae27c73f4029b5eaafe4240

**Comment by renemilk** [comment]
Oh, and foobar as the target branch name? Really?

**Comment by ftalbrecht** [comment]
Thank you for the heavy lifting, I will see what I can do about the float_cmp issue #27. As for the branch name: I should probably clean that up, given my OCD nature^^

**Comment by ftalbrecht** [comment]
I just pushed a complete redone of the merge (dropping foobar^^). The warnings I posted above remain, though! Especially concerning the linear solvers. Does your code still work, @renemilk?
These changes also clean up the `{Const,}GridProvider` situation: as it turns out (some) grid views can be created with a `const GridType&` (and why not!). This is of course not true for grid parts...
So the `ConstGridProvider` now provides all grid views that support const creation (without any `const_cast` remaining) and the `GridProvider` provides the rest. I also refactored the test which should now test some more.
Never the less the `test_grid_walker` test fails for me (did not investigate further) and I am not certain if it is due to my changes or if that one always failed. Any insight is welcome, @renemilk, @tobiasleibner!
I will tackle the float compare issue [#27] next and would like to merge this into the main master then, soon...

**Pull request merged**
