### PR TITLE
Thread-safe expression function

### PR DESCRIPTION
**Pull request by tobiasleibner**
The expression function was not thread-safe, partly because I used a mutable member variable in the evaluate_helper and partly because the evaluate in base.hh is not thread-safe. I fixed the first issue using PerThreadValue. I also spent some time trying to fix the second issue without limiting parallelism but ended up using mutexes because mathexpr.cc and mathexpr.hh is barely readable.

### CODE REVIEW

**Comment by renemilk** [comment]
You should checkout ```std::lock_guard<mutex_type>``` it's much simpler to use than manually locking/unlocking mutexes.
As a stopgap measure this seems fine to me. In the long run that expression parser should die a fiery death, if you ask me :wink:

**Comment by ftalbrecht** [comment]
Looks good to me. If you use the `lock_guard`, you may have to use
```
std::lock_guard< ... > DUNE_UNUSED(guard)(mutex_);
```
from `<dune/common/unused>`, to avoid warnings.

**Comment by tobiasleibner** [comment]
There are no warnings for the lock_guard, so it seems the compiler (gcc) is smart enough. Should I still add the DUNE_UNUSED in case other compilers give a warning?

**Comment by renemilk** [comment]
IIRC it's clang that, imo false positively because side effects, warns on these. If you want check that, or just add it.

**Comment by tobiasleibner** [comment]
Checked, clang also does not warn. 
While we are at unused variable warnings, I am getting some warnings in dune/stuff/test/grid_periodicview.cc for lines like these 
```c++
const GridType& DUNE_UNUSED(test_grid) = periodic_grid_view.grid();
```
despite the DUNE_UNUSED. Am I using it wrong here?

**Comment by renemilk** [comment]
You're not using it wrong. I think the macro definition isn't the best it could be.  Is ```DSC_UNUSED(variable)``` doing better? I've looked into a couple months back and the implementation differs from dune-common's macro. Feel free to fix and or investigate further. A seperate issue would be good in that case. Closing this one with merge.

**Pull request merged**
