### PR TITLE
Use dune-testtools

### PR DESCRIPTION
**Pull request by tobiasleibner**
Not meant to be merged yet.

This uses dune-testtools for the functions_functions, functions_constant and grid_periodicview tests. A separate executable is created for every configuration, which gives >50 executables for the functions tests and 7 for the grid_periodicview test. All compile and execute fine, except for the grid_periodicview test using an
```c++
ALUGrid<3,3,cube,nonconforming>
```
which gives the following linker errors that did not occur before:
```
.../dune-stuff-demos/dune-grid/build-clang-debug/lib/libdunegrid.a(mappings.cc.o):(.rodata+0x8): multiple definition of `Dune::TrilinearMapping::_epsilon'
.../dune-stuff-demos/dune-alugrid/build-clang-debug/lib/libdunealugrid.a(mappings.cc.o):(.rodata+0x8): first defined here
.../dune-stuff-demos/dune-grid/build-clang-debug/lib/libdunegrid.a(mappings.cc.o):(.rodata+0x10): multiple definition of `Dune::BilinearSurfaceMapping::_epsilon'
.../dune-stuff-demos/dune-alugrid/build-clang-debug/lib/libdunealugrid.a(mappings.cc.o):(.rodata+0x10): first defined here
.../dune-stuff-demos/dune-grid/build-clang-debug/lib/libdunegrid.a(mappings.cc.o):(.rodata+0x18): multiple definition of `Dune::SurfaceNormalCalculator::_epsilon'
.../dune-stuff-demos/dune-alugrid/build-clang-debug/lib/libdunealugrid.a(mappings.cc.o):(.rodata+0x18): first defined here
```
I am not quite sure about the CMake changes, maybe I missed something there.

### CODE REVIEW

**Comment by renemilk** [comment]
Excellent! 
That's the old (ie. pre dune-module) ALUgrid, right? And the question of resolving missing alugrid is still open?

**Comment by tobiasleibner** [comment]
Yes, that is the old ALUGrid. But the test did work with that ALUGrid before, and it still does for dimension 2 and the threedimensional simplex conforming ALUGrid. It is just the cube grid in three dimensions that gives this linker error.
If ALUGrid is not present, the executables using ALUGrid should not be compiled at all. There is a preprocessor guard in the grid_periodicview.mini file for that purpose.

**Comment by renemilk** [comment]
Ah, found it. Very nice.
I have no idea wrt to that link error. I generally build w/o ALUGrid.  Did you confirm this as being introduced by the switch to testtools?

**Comment by renemilk** [comment]
Oh, and I'll see about fixing travis today.

**Comment by tobiasleibner** [comment]
Seems to be some random error. I ran dunecontrol again and now its gone.

**Comment by renemilk** [comment]
@tobiasleibner please get the dune-testtols branch from the main repo for travis updates. However  travis does not yet build or run the new tests, as it currently does ```make test_binaries``` and ```make test```. Could we try to hook the new tests into our own stuff or the other way round?

**Comment by renemilk** [comment]
One thing I didn't think of until yesterday evening is that we should fix the dune-{python,testtools}  versions to their release branch. I did that in the testtools branch of the supermodule.  That uncovered an issue with dune-python however: https://gitlab.dune-project.org/quality/dune-testtools/issues/88

 I'm now trying to skip the ```make install``` step that's probably triggering this.  You can adjust the dune-{python/testtools} versions you're using locally right away though, @tobiasleibner

**Comment by tobiasleibner** [comment]
I am already using the releases/2.4 branch of dune-testtools and dune-python locally, no problems here.
With the recent changes, we will now use the dune_add_system_test macro from dune-testtools if there is a .mini file with the same name as the .cc file and else use add_test as we did before. The binaries are added to test_binaries. However, simply executing the binaries will only work if we only use static variations. If we use dynamic variations (see test_grid_periodicview), the correct .ini file has to be added to the call. The corresponding CTests should automatically link the correct ini.

**Comment by renemilk** [comment]
Very nicely done! I've pushed a working travis config to the main repo a couple of minutes ago too.

**Comment by tobiasleibner** [comment]
Some of the travis builds are timing out, propably because building all the tests takes longer now. Can you increase the allowed time @renemilk ?

**Comment by renemilk** [comment]
Lets try https://travis-ci.org/wwu-numerik/dune-stuff/builds/96227257 in https://travis-ci.org/wwu-numerik/dune-stuff/builds/96227257 first. Otherwise one can prefix commands with ```travis_wait``` or ```travis_retry```

**Comment by tobiasleibner** [comment]
Closed in favor of #96.

**Pull request closed without merging**
